### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spongycode**
added some screenshots and described it bit more.

### CODE REVIEW

**Comment by Godstyme** [comment]
Thanks.
Star the project and also add this statement to the readme file "Don't forget to give this Repository a ⭐!"

**Comment by spongycode** [comment]
Done 👍

**Comment by Godstyme** [comment]
Thanks brother.
I will merge your PR now.
Happy hacking.

**Comment by Godstyme** [comment]
happy hacking
Hacktober team will review as well👍

**Pull request merged**
